CREATE TYPE "access" AS ENUM (
  'public',
  'private'
);

CREATE TABLE "services" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "api_name" varchar,
  "api_key" varchar,
  "endpoint" varchar,
  "base_url" varchar,
  "port" varchar,
  "access_type" access,
  "created_at" timestamp DEFAULT(now()),
  PRIMARY KEY ("api_name", "api_key", "endpoint", "base_url", "port")
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar,
  "password" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "flagged_services" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "api_name" varchar,
  "base_url" varchar,
  "port" varchar,
  PRIMARY KEY ("api_name", "base_url", "port")
);
