CREATE TYPE "auth" AS ENUM (
  'user',
  'admin',
  'all'
);

CREATE TABLE "services" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "api_name" varchar,
  "api_key" varchar,
  "endpoint" varchar,
  "base_url" varchar,
  "port" integer,
  "access_type" auth,
  "created_at" timestamp,
  PRIMARY KEY ("api_name", "api_key", "endpoint", "base_url", "port")
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar,
  "password" varchar,
  "role" varchar,
  "created_at" timestamp
);
